/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url = "https://repo.casterlabs.co/caffeinated")
    maven(url = "https://jitpack.io/")
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    //Casterlabs Caffeinated PluginSDK
    compileOnly("co.casterlabs:PluginSDK:1.2")

    //JDBC SQLite library
    implementation("org.xerial:sqlite-jdbc:3.42.0.0")

    //lombok Java annotations
    compileOnly("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")

    testCompileOnly("org.projectlombok:lombok:1.18.28")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.28")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.8.2")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.ayrlin.tasukaru.App")
}

tasks.register("export", Copy::class) {
    from("$buildDir/libs/app.jar") // Source file path
    into("${System.getenv("APPDATA")}/casterlabs-caffeinated/plugins") // Destination directory path (appdata/path)

    rename("app.jar", "tasukaru.jar")
}

// Java 11 Eclipse Adoptium
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}